---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - traefik.containo.us
  resources:
  - ingressroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - traefik.containo.us
  resources:
  - ingressroutes/finalizers
  verbs:
  - update
- apiGroups:
  - traefik.io
  resources:
  - ingressroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - traefik.io
  resources:
  - ingressroutes/finalizers
  verbs:
  - update
