---
name: test (go)
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Make test
        run: |
          make test

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: cover.out
          report: true
          chart: false
          amend: false
          reuse-go: true
        if: |
          github.event_name == 'push'
        continue-on-error: false
